[project]
site_name = "ShaderFlow"
site_description = "🔥 Modular shader engine designed for simplicity and speed"
site_author = "Tremeschin"
site_url  = "https://shaders.tremeschin.com/"
repo_url  = "https://github.com/BrokenSource/ShaderFlow/"
repo_name = "BrokenSource/ShaderFlow"
copyright = "&copy; CC BY-SA 4.0, <a href='https://github.com/Tremeschin/'>Tremeschin</a> 🇧🇷"
docs_dir  = "website"
nav = [
  {Origin = "https://tremeschin.com/"},
  {Home = [
    "index.md",
    "changelog.md",
    "license.md",
  ]},
  {Get = [
    "get/pypi.md",
    # "get/pyaket.md",
    "get/source.md",
    "get/docker.md",
  ]},
  {Show = [
    "show/index.md",
  ]},
  {Docs = [
    "docs/index.md",
    "docs/module.md",
    "docs/scene.md",
    "docs/camera.md",
    "docs/shader.md",
    "docs/texture.md",
  ]},
  {FAQ = [
    "faq/index.md",
    {Base = [
      "faq/general.md",
    ]},
    {Systems = [
      "faq/windows.md",
      "faq/linux.md",
      "faq/macos.md",
    ]}
  ]},
]
[project.theme]
name = "zentheme"
favicon = "assets/logo.png"

[project.theme.icon]
logo = "octicons/flame-16"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/KjqvcYwRHm"
name = "Discord"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Tremeschin"
name = "GitHub"

[[project.extra.social]]
icon = "simple/githubsponsors"
link = "https://github.com/sponsors/Tremeschin"
name = "GitHub Sponsors"

[[project.extra.social]]
icon = "fontawesome/brands/patreon"
link = "https://www.patreon.com/Tremeschin"
name = "Patreon"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@Tremeschin"
name = "YouTube"
