blank_issues_enabled: true
contact_links:
  - name: ✅ Discord and Telegram groups
    url: https://brokensrc.dev/about/contact/
    about: "Get in touch for faster, real-time responses. We can formalize the issue on GitHub later!"
